package banque;


/**
* banque/ComptePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Wednesday, April 12, 2017 1:38:07 PM CEST
*/

public abstract class ComptePOA extends org.omg.PortableServer.Servant
 implements banque.CompteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_titulaire", new java.lang.Integer (0));
    _methods.put ("_set_titulaire", new java.lang.Integer (1));
    _methods.put ("_get_solde", new java.lang.Integer (2));
    _methods.put ("crediter", new java.lang.Integer (3));
    _methods.put ("debiter", new java.lang.Integer (4));
    _methods.put ("infosCompte", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // banque/Compte/_get_titulaire
       {
         String $result = null;
         $result = this.titulaire ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // banque/Compte/_set_titulaire
       {
         String newTitulaire = in.read_string ();
         this.titulaire (newTitulaire);
         out = $rh.createReply();
         break;
       }

       case 2:  // banque/Compte/_get_solde
       {
         float $result = (float)0;
         $result = this.solde ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // banque/Compte/crediter
       {
         float somme = in.read_float ();
         boolean $result = false;
         $result = this.crediter (somme);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // banque/Compte/debiter
       {
         float somme = in.read_float ();
         boolean $result = false;
         $result = this.debiter (somme);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // banque/Compte/infosCompte
       {
         String $result = null;
         $result = this.infosCompte ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:banque/Compte:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Compte _this() 
  {
    return CompteHelper.narrow(
    super._this_object());
  }

  public Compte _this(org.omg.CORBA.ORB orb) 
  {
    return CompteHelper.narrow(
    super._this_object(orb));
  }


} // class ComptePOA
