package banque;


/**
* banque/CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Wednesday, April 12, 2017 1:38:07 PM CEST
*/

public interface CompteOperations 
{
  String titulaire ();
  void titulaire (String newTitulaire);
  float solde ();
  boolean crediter (float somme);
  boolean debiter (float somme);
  String infosCompte ();
} // interface CompteOperations
