package banque;


/**
* banque/CompteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Wednesday, April 12, 2017 1:38:07 PM CEST
*/

abstract public class CompteHelper
{
  private static String  _id = "IDL:banque/Compte:1.0";

  public static void insert (org.omg.CORBA.Any a, banque.Compte that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static banque.Compte extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (banque.CompteHelper.id (), "Compte");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static banque.Compte read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CompteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, banque.Compte value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static banque.Compte narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof banque.Compte)
      return (banque.Compte)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      banque._CompteStub stub = new banque._CompteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static banque.Compte unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof banque.Compte)
      return (banque.Compte)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      banque._CompteStub stub = new banque._CompteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
