package banque;

/**
* banque/CompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Wednesday, April 12, 2017 1:38:07 PM CEST
*/

public final class CompteHolder implements org.omg.CORBA.portable.Streamable
{
  public banque.Compte value = null;

  public CompteHolder ()
  {
  }

  public CompteHolder (banque.Compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banque.CompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banque.CompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banque.CompteHelper.type ();
  }

}
