package commerces;


/**
* commerces/DistributeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributeur.idl
* Tuesday, June 13, 2017 3:52:07 PM CEST
*/

public interface DistributeurOperations 
{
  String modeleDistributeur();
  void modeleDistributeur(String newModeleDistributeur);
  float solde();
  boolean crediter(org.omg.CORBA.Object compte, int somme);
  boolean debiter(org.omg.CORBA.Object compte, int somme);
  String infosDistributeur();
} // interface DistributeurOperations
