package commerces;


/**
* commerces/DistributeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributeur.idl
* Wednesday, June 14, 2017 10:05:28 AM CEST
*/

public interface DistributeurOperations 
{
  String modeleDistributeur ();
  void modeleDistributeur (String newModeleDistributeur);
  boolean canCrediter ();
  void canCrediter (boolean newCanCrediter);
  boolean crediter (org.omg.CORBA.Object compte, int somme);
  boolean debiter (org.omg.CORBA.Object compte, int somme);
  String infosDistributeur ();
} // interface DistributeurOperations
