module commerces {
    interface Distributeur {
        attribute string modeleDistributeur;
        attribute boolean canCrediter;
        boolean crediter(in Object compte, in long somme);
        boolean debiter(in Object compte, in long somme);
        string infosDistributeur();
    };
};