package commerces;


/**
* commerces/Distributeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributeur.idl
* Wednesday, June 14, 2017 10:05:28 AM CEST
*/

public interface Distributeur extends DistributeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Distributeur
