package commerces;


/**
* commerces/Distributeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributeur.idl
* Tuesday, June 13, 2017 3:52:07 PM CEST
*/

public interface Distributeur extends DistributeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Distributeur
